### ISSUE TITLE
Refactor APIs for Items

### ISSUE THREAD

**Issue by kdokm** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#114]
**As a** developer
 **I need** to refactor the code using a more advanced framework
 **So that** I can have generated documentation automatically
   
 ### Details and Assumptions
 * Using Flask-RESTX and Swagger
 * Refactor the /shopcarts/{user_id}/items and /shopcarts/{user_id}/items/{item_id} routes
 * Make sure all of the proper error codes returned (~e.g. 400 for an invalid user_id or item_id meaning not a non-negative integer, NOT 404~) [EDIT: prof said default 404 for those is the right thing to do so switch back to /shopcarts/\<int:user_id\>] :(
 * After refactoring use ```flask routes``` to list all routes, make sure there are no static gets or other routes not specified by our API explicitly.
 * [UPDATE] Can delete MOST of (probably not all) error_handler.py when this is done since Flask_RESTX will handle errors automatically 

 ### Acceptance Criteria  
   
 ```gherkin
 Given we have refactored the above routes
 When we run nosetests and behave on the tests we had previously written on these routes
 Then all tests pass
 ```

**Comment by TimothyXu** [comment]
can put swagger tags (for auto-generating docs0 in a different story if need be

**Comment by TimothyXu** [comment]
Copying my comment in the GitHub PR for bookkeeping purposes. Most of the work is done which is great! Refactoring is fine. But 3 issues to deal with:

1. As prof said in our slack channel, A 400_BAD_REQUEST is reserved for the payload. Not the path. so we need to change all the urls back to int:shopcart_id etc. and not check for them manually. And when we try to call e.g. /shopcarts/wrongid we should get the default 404 from Flask and that's fine.
2. Once this is done we should also delete most of error_handlers.py so they don't impact our nosetests coverage
3. Unless I'm understanding HTML incorrectly due to not knowing any front end, we need to get rid of the static get route at /static/path:filename.

**Comment by TimothyXu** [comment]
1 and 2 done, need to possibly do 3 (please someone who knows how websites work chime in lol)
