### ISSUE TITLE
Create .github/workflows/bdd.yml file and configure github Actions

### ISSUE THREAD

**Issue by yjjw** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#63]
**As a** developer 
 **I need to** create a  .github/workflows/bdd.yml file and configure Github Actions 
 **So that** integration test cases are run every time main branch is updated or a Pull Request to the main branch is submitted
   
 ### Details and Assumptions
 * integration test cases are run every time main branch is updated or a Pull Request to the main branch is submitted
 * Follow the GitHub Actions syntax in the yml file, taught in a previous lecture

 ### Acceptance Criteria  
   
 ```gherkin
 Given GitHub actions have been set up correctly with the bdd.yml file
 When a pull request to main or when that pull request is accepted
 Then the integration tests automatically run according to the specifications of the yml file.
 ```

**Comment by kdokm** [comment]
Hi @lemadmax ! I think you should only have one work in progress at any time, according to what we learned in class.

**Comment by TimothyXu** [comment]
Agreed per Agile, @lemadmax please only assign the top issue to yourself. I'll remove this assignment here

**Comment by TimothyXu** [comment]
Hi @lemadmax so I thought you had already worked on this story since you assigned 2 stories to yourself a few days ago including this one, so I thought you should have this story. But now that I understand this story is only about making GitHub Actions run Behave, perhaps you haven't actually worked on it, in which case feel free to unassigned yourself and someone else can take it
