### ISSUE TITLE
Update Shopcarts

### ISSUE THREAD

**Issue by lemadmax** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#7]
**As a** user  
 **I need** to be able to update my shopcart  
 **So that** I can store exactly the things I want in my shopcart  
   
 ### Details and Assumptions
 * PUT method should be used, along with body containing an item and the quantity desired
 * Expecting new item, quantity and status code 200 as well as the if update successful; expect status code code 404 if shopcart not found; expect status code 406 if quantity is not a non-negative integer. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the local service is running and there is a shopcart
 When we call PUT with body itemID and quantity on the relevant shopcart
 Then returns status code, maybe item, quantity as defined above
 ```

**Comment by yjjw** [comment]
Could we break Create/Read/Update/Delete to four different stories so each story just focuses on one part?

**Comment by TimothyXu** [comment]
> Could we break Create/Read/Update/Delete to four different stories so each story just focuses on one part?

Agreed, this story is only for update. Need other 3 too.

**Comment by TimothyXu** [comment]
Changed details and acceptance since according to REST conventions (given in lecture), PUT must be idempotent (calling same PUT request multiple times should be the same as calling it once). Hence instead of an operation parameter (add/delete), we use a quantity parameter for the amount we want to update to.
